name: "Packaging Test"

on:
  push:
    branches: [main]
  pull_request: {}
jobs:
  check_packaging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: uv sync --group packaging
      - name: Run Packaging Test
        run: |
          uv run python -m build
          uv run twine check dist/*
